### ISSUE TITLE
OS language not applied

### ISSUE THREAD

**Issue by pled** [kirienko/gourmet#340] opened 2021-06-03 08:40 UTC
After installing `gourmet-c3ece056.flatpak`on Ubuntu 20.04 with locales set to FR, Gourmet menus are still in English.

### Steps to Reproduce
1. install `gourmet-c3ece056.flatpak` on Ubuntu 20.04 FR
2. run Gourmet
3. menus are in English language

### Expected Behavior
Menus should be in French

### Current OS settings
$ locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

### Database
I was previously running Gourmet 0.17 (deb package). I uninstalled it. 
After installing new `gourmet-c3ece056.flatpak`, all recipes were automatically filled in that new version (no import needed).

### Environment
* Operating System: Ubuntu 20.04.2 LTS
* Version or commit id: core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
* Installed as Flatpak or Python package?: Flatpak

**Comment by cydanil** [comment] 2021-06-13 20:09
Salut,
thanks for reporting the issue!  
I remember that it was further investigated in https://github.com/thinkle/gourmet/issues/1017, where the problem is nicely described.  
I will look into resolving it.   
It's not going to be immediate, though, but should be fixed in 2 releases from now.

**Comment by pled** [comment] 2021-06-14 08:18
Thanks Cyril, you may close this one or set as duplicate. Sorry I missed thinkle#1017.

**Comment by cydanil** [comment] 2021-06-19 21:51
Hi,  
I'm slowly making progress with this the localization.  

I see that few fields are translated:  
![image](https://user-images.githubusercontent.com/2159577/122656257-0e786d80-d159-11eb-8d19-0ed71e72129f.png)


Would you expect more of the application to be in French?  
I'm asking in order to figure out how much of the internationalization is broken.

**Comment by pled** [comment] 2021-06-20 08:28
Hi Cyril,
Honestly, I would expect every field to be translated... in a perfect world ! ;) 
Now, this does not prevent me to use Gourmet, even with all fields in English. 
So it depends I suppose on how long it would take to repare the internationalization. 
Up to you to decide, it is already so nice to have Gourmet with Python 3 running ! Thank you and all the people involved for that.
I cannot help in dev, but if you need someone to test or help, let me know.
Thank you.

**Comment by cydanil** [comment] 2021-06-20 12:19
Thanks for the feedback, I'm now able to run the application in different locales:  

![image](https://user-images.githubusercontent.com/2159577/122673834-8e8ee980-d1d2-11eb-8525-de10f2c8eb6b.png)

**Closed as completed** 2021-06-29 15:29 UTC

**Comment by cydanil** [comment] 2021-06-29 15:36
This is at last fixed!  
I'll be creating a new release in the coming days with it all.
