### ISSUE TITLE
Adding New Recipe Does Not Update Index Properly

### ISSUE THREAD

**Issue by zombiewoof** [kirienko/gourmet#228] opened 2020-10-03 15:50 UTC
When adding new recipe, index is incorrectly updated. Behavior differs if viewing last index page vs any other, as described below.

Choose Add Recipe when viewing any index page, except the last. When new recipe is saved, use the Last button to go to the last index page. New entry does not display name or thumbnail and cuisine, rating and source are missing. Screenshot shows this and the result of double-clicking the new recipe (display of edit window instead of recipe card).

![Gourmet add recipe 1 2020-10-03 11-29-32](https://user-images.githubusercontent.com/4460090/94995450-5e33ec00-056c-11eb-96c0-41896e5380ff.png)

When same test is run while viewing the last index page, the new recipe does not show up until the Last button is clicked. Again, the index is incorrectly updated, as before. However, the previous test recipe shows up correctly, now. Screenshot shows this and the result of double-clicking the new recipe (display of edit window instead of recipe card).

![Gourmet add recipe 2 2020-10-03 11-44-48](https://user-images.githubusercontent.com/4460090/94995701-0e562480-056e-11eb-991b-11990f9aab1b.png)

### Environment
gourmet-5ad618be
Operating System: Ubuntu 20.04 (with latest updates)
Desktop: Cinnamon 4.4.8
Installed as Flatpak

**Comment by cydanil** [comment] 2020-10-03 17:33
Thanks, this is a confirmation of #196 and thinkle/gourmet/issues/962 .
Since this ticket has the most infos, I'm closing the other ticket.

**Comment by zombiewoof** [comment] 2020-10-04 15:39
You should note that this behavior is slightly different to the python2 version of Gourmet. In that version, if you are on the last index page, the new recipe is added to the index correctly. If one is on another index page, when adding, the same behavior as reported for python3 version occurs.

**Comment by cydanil** [comment] 2020-10-05 13:25
Thanks!
Just like #227 , this was caused by changes in the `[hide method`](https://github.com/kirienko/gourmet/pull/132/files#diff-f8ba652dac21fa98c3f63d5592c79174R134-R140) modified in PR #132.

This was fixed in #235 .

**Closed as completed by cydanil** 2020-10-05 13:25 UTC
Labels: bug
