### ISSUE TITLE
Printing & PDF Export Not working

### ISSUE THREAD

**Issue by ghost** [kirienko/gourmet#370] opened 2021-08-01 19:32 UTC
I checked the Settings menu, then Plugins and see the plug-in is active. However, it is not functioning correctly. I can't even print with this plugin active. I also get a Deactivation Error when I try to deactivate the plugin to attempt resetting it.

### Steps to Reproduce

1. Select Example Recipe > Main Menu > Print > Error: "Unable to Print: No Print Plugins Active"
2. Check Settings > Plugins > Print & PDF Export Plugin Marked Active (Green Check Marked)
3. Attempted to reset plugin by deactivation/unchecking it > Error: "Unable to Deactivate".

### Expected Behavior

Expected Behavior is with plugins marked active, I should have no trouble printing recipes.
### Current Behavior
- Expected flawless printing of example recipes. 
- See Steps to Reproduce for error messages.
-->

### Possible Solution
- Fix the plugin framework or code to eliminate such errors. I suspect their is a communication error between the basic application structure and plugins themselves. Of course, I am not a software developer by trade. So this guess may not be accurate.

### Environment
Running Linux Mint 20+ with Cinnamon Desktop, No printing issues with other installed apps.
Running Gourmet Version: 0.17.5
Using Flatpak version: gourmet-2db9db8f.flatpak

**Comment by ghost** [comment] 2021-08-01 19:43
I read some other issue tickets and learned that I need to install version 1.0.0. however, i need to manually install the flatpak from here on github. The problem is I keep getting a 404 error page when attempting to get to the manual installation page from a link in the "install.md" page.

**Comment by cydanil** [comment] 2021-08-06 18:39
Thanks for the report.  
I'm now working on this, but will close this issue as a duplicate of #369, where the discussion will be :)

**Closed as completed by cydanil** 2021-08-06 18:39 UTC

**Comment by ghost** [comment] 2021-08-07 20:42
Thanks for taking care of this. I can wait for the next release. Hopefully you also get that 404 Error page for the flatpak file in "install.md" taken care of as well.

**Comment by cydanil** [comment] 2021-08-07 20:52
Yes! I have made a note of updating the links 🙂
